<form method="post" action="/edit_task">
    <input type="hidden" name="task_id" value="<?php echo $this->task_id; ?>">
    <div class="form-group">
        <input class="form-control" readonly type="text" value="<?php echo $this->name; ?>">
    </div>
    <div class="form-group">
        <input class="form-control" readonly type="text" value="<?php echo $this->email; ?>">
    </div>
    <div class="form-group">
        <textarea class="form-control" name="task_text" rows="3"><?php echo $this->task_text; ?></textarea>
    </div>

    <div class="form-group">
        <label for="exampleFormControlSelect1">Статус задачи:</label>
        <select class="form-control" name="task_status" id="exampleFormControlSelect1">
            <option value="1"<?php if ($this->status === 'done') { echo ' selected'; } ?>>Done</option>
            <option value="0"<?php if ($this->status === 'doing') { echo ' selected'; } ?>>Doing</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary mb-2">Сохранить</button>
</form>