
<?php foreach ($this->errors as $error): ?>
    <div class="alert alert-danger" role="alert">
        <?php echo $error; ?>
    </div>
<?php endforeach; ?>

<form method="post" action="/auth">
    <div class="form-group">
        <input class="form-control" name="login" type="text" placeholder="Логин">
    </div>
    <div class="form-group">
        <input class="form-control" name="password" type="password" placeholder="Пароль">
    </div>
    <button type="submit" class="btn btn-primary mb-2">Войти</button>
</form>